"""'test'

Revision ID: 9f54eddde0be
Revises: 0e8873ee37d3
Create Date: 2022-05-01 18:01:20.694495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f54eddde0be'
down_revision = '0e8873ee37d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacation', sa.Column('date_created', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacation', 'date_created')
    # ### end Alembic commands ###
